#!/usr/bin/env python3
"""Project/action-set layer for SpriteForge Studio."""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

ROOT = Path(__file__).resolve().parent
DEFAULT_ACTIONS = ["idle", "walk", "run", "attack_light", "hurt"]
DEFAULT_DIRECTIONS = ["right"]


def split_csv(value: str) -> List[str]:
    return [x.strip() for x in value.split(",") if x.strip()]


def run(cmd: List[str], cwd: Optional[Path] = None) -> None:
    print("$ " + " ".join(cmd))
    subprocess.run(cmd, cwd=str(cwd or ROOT), check=True)


def load_project(path: Path) -> Dict[str, Any]:
    if path.is_dir():
        path = path / "spriteforge_project.json"
    return json.loads(path.read_text(encoding="utf-8"))


def project_root(path: Path) -> Path:
    return path if path.is_dir() else path.parent


def cmd_init(args: argparse.Namespace) -> None:
    out = Path(args.output or (ROOT / "projects" / args.name)).resolve()
    out.mkdir(parents=True, exist_ok=True)
    for d in ["references", "posepacks", "prompts", "sprites", "exports", "quality", "cloud_jobs"]:
        (out / d).mkdir(exist_ok=True)
    actions = split_csv(args.actions) if args.actions else DEFAULT_ACTIONS
    directions = split_csv(args.directions) if args.directions else DEFAULT_DIRECTIONS
    project = {
        "schema": "spriteforge_project_v1",
        "name": args.name,
        "character": args.character,
        "style": args.style,
        "background": args.background,
        "profile": args.profile,
        "mode": args.mode,
        "actions": actions,
        "directions": directions,
        "fps": args.fps,
        "cell_size": args.cell_size,
        "frames_by_action": {
            "idle": 24,
            "walk": 33,
            "run": 25,
            "attack_light": 24,
            "attack_heavy": 32,
            "cast": 32,
            "jump": 24,
            "hurt": 16,
            "death": 40,
        },
        "notes": "Generated by SpriteForge Studio. Edit this JSON to change action set defaults.",
    }
    path = out / "spriteforge_project.json"
    path.write_text(json.dumps(project, indent=2), encoding="utf-8")
    print(f"Project: {path}")


def prompt_command(project: Dict[str, Any], root: Path, action: str, direction: str) -> List[str]:
    out = root / "prompts" / f"{action}_{direction}.json"
    return [
        sys.executable, str(ROOT / "spriteforge_unified.py"), "build-prompt",
        "--action", action,
        "--direction", direction,
        "--character", project["character"],
        "--style", project["style"],
        "--background", project["background"],
        "--pose-guided",
        "--output", str(out),
    ]


def pose_command(project: Dict[str, Any], root: Path, action: str, direction: str) -> List[str]:
    frames = int(project.get("frames_by_action", {}).get(action, 24))
    out = root / "posepacks" / f"{action}_{direction}"
    return [
        sys.executable, str(ROOT / "spriteforge_unified.py"), "make-posepack",
        "--action", action,
        "--direction", direction,
        "--frames", str(frames),
        "--size", "512",
        "--output", str(out),
    ]


def generate_command(project: Dict[str, Any], root: Path, action: str, direction: str) -> List[str]:
    frames = int(project.get("frames_by_action", {}).get(action, 24))
    out_prefix = f"{project['name']}_{action}_{direction}"
    return [
        sys.executable, str(ROOT / "spriteforge_unified.py"), "generate-sprite",
        "--start-comfy",
        "--mode", project.get("mode", "t2v"),
        "--profile", project.get("profile", "rtx3060_12gb"),
        "--action", action,
        "--direction", direction,
        "--character", project["character"],
        "--style", project["style"],
        "--background", project["background"],
        "--frames", str(frames),
        "--video-fps", str(project.get("fps", 12)),
        "--output-prefix", out_prefix,
    ]


def cmd_assets(args: argparse.Namespace) -> None:
    p = Path(args.project).resolve()
    root = project_root(p)
    project = load_project(p)
    for action in project["actions"]:
        for direction in project["directions"]:
            run(prompt_command(project, root, action, direction))
            run(pose_command(project, root, action, direction))
    print("Project prompt/pose assets generated.")


def cmd_plan(args: argparse.Namespace) -> None:
    p = Path(args.project).resolve()
    root = project_root(p)
    project = load_project(p)
    lines = []
    lines.append(f"# SpriteForge production plan: {project['name']}")
    lines.append("")
    lines.append("## 1. Build prompt and pose assets")
    lines.append(f"python spriteforge_unified.py project-assets --project \"{root / 'spriteforge_project.json'}\"")
    lines.append("")
    lines.append("## 2. Generate each action")
    for action in project["actions"]:
        for direction in project["directions"]:
            lines.append(" ".join(f'\"{x}\"' if " " in x else x for x in generate_command(project, root, action, direction)))
    lines.append("")
    lines.append("## 3. Quality check every sprite output")
    for action in project["actions"]:
        for direction in project["directions"]:
            probable = ROOT / "output" / f"{project['name']}_{action}_{direction}_sprite"
            lines.append(f"python spriteforge_unified.py quality-check --sprite-dir \"{probable}\"")
    lines.append("")
    lines.append("## 4. Build atlas from completed action folders")
    lines.append(f"python spriteforge_unified.py atlas-build --root \"{ROOT / 'output'}\" --output \"{root / 'exports' / (project['name'] + '_atlas')}\" --name \"{project['name']}\" --name-from-folder")
    out = root / "production_plan.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Plan: {out}")


def cmd_summary(args: argparse.Namespace) -> None:
    p = Path(args.project).resolve()
    root = project_root(p)
    project = load_project(p)
    print(json.dumps(project, indent=2))
    print(f"Root: {root}")
    for d in ["references", "posepacks", "prompts", "sprites", "exports", "quality", "cloud_jobs"]:
        path = root / d
        print(f"{d}: {len(list(path.glob('**/*'))) if path.exists() else 0} files")


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="SpriteForge project manager")
    sub = p.add_subparsers(dest="command", required=True)
    s = sub.add_parser("init")
    s.add_argument("--name", required=True)
    s.add_argument("--character", default="single full body original game character, consistent outfit, readable silhouette")
    s.add_argument("--style", default="2D game sprite animation, crisp edges, readable silhouette, production sprite sheet style")
    s.add_argument("--background", default="plain bright green chroma key background, evenly lit, no shadows on background")
    s.add_argument("--actions", default=",".join(DEFAULT_ACTIONS))
    s.add_argument("--directions", default=",".join(DEFAULT_DIRECTIONS))
    s.add_argument("--profile", default="rtx3060_12gb")
    s.add_argument("--mode", default="t2v")
    s.add_argument("--fps", type=int, default=12)
    s.add_argument("--cell-size", default="512x512")
    s.add_argument("--output", default=None)
    s.set_defaults(func=cmd_init)

    s = sub.add_parser("assets")
    s.add_argument("--project", required=True)
    s.set_defaults(func=cmd_assets)

    s = sub.add_parser("plan")
    s.add_argument("--project", required=True)
    s.set_defaults(func=cmd_plan)

    s = sub.add_parser("summary")
    s.add_argument("--project", required=True)
    s.set_defaults(func=cmd_summary)
    return p


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    args.func(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
